CREATE TABLE fin.INVOICES (
    Id UNIQUEIDENTIFIER NOT NULL,
    Invoice_Date DATETIME NOT NULL,
    Amount DECIMAL NOT NULL,
    Payment_Method VARCHAR (100) NOT NULL,
    Payee VARCHAR (100) NOT NULL,
    Detail VARCHAR (4000) NULL,
	CONSTRAINT PK_INVOICES_ID PRIMARY KEY (Id)
);

SELECT * FROM fin.INVOICES WHERE Payee = 'EAAAAAAAAAA';

INSERT INTO fin.INVOICES VALUES (NEWID(), '2022-05-30 04:10:06', 0, 'Cash', 'EA', '');

CREATE TABLE fin.CATEGORIES (
    Id UNIQUEIDENTIFIER NOT NULL,
    Nombre VARCHAR(100),
    CONSTRAINT PK_CATEGORIES_ID PRIMARY KEY (Id),
    CONSTRAINT UQ_CATEGORIES_Nombre UNIQUE (Nombre)
);

SELECT * FROM fin.CATEGORIES;

INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'Car');
INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'Health');
INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'Groceries')