CREATE TABLE fin.INVOICES (
    Id UNIQUEIDENTIFIER NOT NULL,
    Invoice_Date DATETIME NOT NULL,
    Amount DECIMAL NOT NULL,
    Payment_Method VARCHAR (100) NOT NULL,
    Payee VARCHAR (100) NOT NULL,
    Detail VARCHAR (4000) NULL,
	CONSTRAINT PK_INVOICES_ID PRIMARY KEY (Id)
);

SELECT * FROM fin.INVOICES;

INSERT INTO fin.INVOICES VALUES (NEWID(), '2022-05-30 04:10:06', 0, 'Cash', 'EA', '');

CREATE TABLE fin.CATEGORIES (
    Id UNIQUEIDENTIFIER NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CATEGORIES_ID PRIMARY KEY (Id),
    CONSTRAINT UQ_CATEGORIES_NOMBRE UNIQUE (Nombre)
);

SELECT * FROM fin.CATEGORIES;

INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'Car');
INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'Health');
INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'Groceries');
INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'No category');
INSERT INTO fin.CATEGORIES VALUES (NEWID(), 'Eating out');

ALTER TABLE fin.INVOICES ADD Category UNIQUEIDENTIFIER NULL;
ALTER TABLE fin.INVOICES ADD CONSTRAINT FK_INVOICES_CATEGORY FOREIGN KEY (Category) REFERENCES fin.CATEGORIES (Id);
UPDATE fin.INVOICES SET Category = '74d6ca69-e46c-41de-854f-d602d76cdfa0';
ALTER TABLE fin.INVOICES ALTER COLUMN Category UNIQUEIDENTIFIER NOT NULL;
